// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "7ec996d5-aa0b-4258-92b2-9d5348c51059";

const char SSID[]               = "TECNO POP 7 pro";    // Network SSID (name)
const char PASS[]               = "today0118";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "WM4ClVt6ywOVgHTpYSUcqljp1";    // Secret device password

void onMessageChange();
void onBalanceChange();

String message;
float balance;
float energy_consumption;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(message, READWRITE, ON_CHANGE, onMessageChange);
  ArduinoCloud.addProperty(balance, READWRITE, ON_CHANGE, onBalanceChange);
  ArduinoCloud.addProperty(energy_consumption, READ, 10 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

