/* 
  Sketch generated by the Arduino IoT Cloud Thing "Ventilator Things"
  https://create.arduino.cc/cloud/things/07eb97b0-541a-4f1d-98f0-526cec8378a8 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float ecg;
  float heartRate;
  float pressure;
  float spo2;
  float temp;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include <ESPComm.h>
#include "thingProperties.h"

ESPComm esp(Serial);

void onReceive(String key, String value) {
  if (key == "temp") {
    temp = value.toFloat();
  } else if (key == "spo2") {
    spo2 = value.toFloat();
  } else if (key == "pressure") {
    pressure = value.toFloat();
  } else if (key == "heartRate") {
    heartRate = value.toFloat();
  } else if (key == "ecg") {
    ecg = value.toFloat();
  }
}

void setup() {
  // Initialize serial and wait for port to open:
  esp.begin(9600);
  esp.onCommand(onReceive);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
}

void loop() {
  esp.loop();
  ArduinoCloud.update();
}
