// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[] = "350c5df6-21e8-4675-b72f-e628db5d7df1";

const char SSID[] = "OIC_";              // Network SSID (name)
const char PASS[] = "oichub@@1920";     // Network password (use for WPA, or use as key for WEP)
// const char SSID[] = "ventilator";              // Network SSID (name)
// const char PASS[] = "atbu1212";     // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[] = "tJsd3K8W7E!Mj9A@vfDGHuEJB";  // Secret device password


float ecg;
float heartRate;
float pressure;
float spo2;
float temp;

void initProperties() {

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(ecg, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(heartRate, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(pressure, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(spo2, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(temp, READ, 10 * SECONDS, NULL);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
